-- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM
    (SELECT A.ITEM_ID
     FROM ITEM_TREE A LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
     WHERE B.ITEM_ID IS NULL) T JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
ORDER BY ITEM_ID DESC;