SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD UB, USED_GOODS_USER UU
WHERE UB.WRITER_ID = UU.USER_ID
AND STATUS = 'DONE'
GROUP BY UB.WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES