-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) YEAR, (B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A, 
(SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;
