-- 코드를 작성해주세요
SELECT E.ID, IFNULL(A.COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA E LEFT JOIN
     (SELECT PARENT_ID, COUNT(*) COUNT
      FROM ECOLI_DATA
      GROUP BY PARENT_ID
      HAVING PARENT_ID IS NOT NULL) A ON E.ID = A.PARENT_ID
ORDER BY E.ID;