-- 코드를 입력하세요
SELECT H.HISTORY_ID, ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE *
                          (CASE
                            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN 0.9
                            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN 0.93
                            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN 0.95
                            ELSE 1
                            END)) FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC