WITH RECURSIVE R AS (
    SELECT 0 as hour
    UNION ALL
    SELECT hour + 1
    FROM R
    WHERE hour < 23
)

SELECT R.hour HOUR, COUNT(ANIMAL_ID) COUNT
FROM R LEFT JOIN ANIMAL_OUTS AO ON R.hour = HOUR(AO.DATETIME)
GROUP BY R.hour
ORDER BY HOUR