SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI, (SELECT FISH_TYPE, MAX(LENGTH) L
                    FROM FISH_INFO
                    GROUP BY FISH_TYPE) M, FISH_NAME_INFO FNI
WHERE FI.FISH_TYPE = M.FISH_TYPE AND FI.FISH_TYPE = FNI.FISH_TYPE AND LENGTH = M.L
ORDER BY ID