SELECT D.ID
FROM ECOLI_DATA D JOIN (SELECT A.ID
                        FROM ECOLI_DATA A JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
                        WHERE B.PARENT_ID IS NULL) C
ON D.PARENT_ID = C.ID
ORDER BY D.ID