-- 코드를 작성해주세요
SELECT E.ID,
       CASE
           WHEN A.NAME = 4 THEN 'CRITICAL'
           WHEN A.NAME = 3 THEN 'HIGH'
           WHEN A.NAME = 2 THEN 'MEDIUM'
           WHEN A.NAME = 1 THEN 'LOW'
           END COLONY_NAME
FROM ECOLI_DATA E JOIN (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) AS NAME
    FROM ECOLI_DATA
    ORDER BY ID
) A ON E.ID = A.ID;