SELECT F.ID, CASE S.N
                WHEN 1 THEN 'CRITICAL'
                WHEN 2 THEN 'HIGH'
                WHEN 3 THEN 'MEDIUM'
                WHEN 4 THEN 'LOW'
                END COLONY_NAME
FROM ECOLI_DATA F, (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) N FROM ECOLI_DATA) S
WHERE F.ID = S.ID
ORDER BY F.ID