-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM (SELECT USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
      FROM ONLINE_SALE) O
      JOIN (SELECT USER_ID, GENDER FROM USER_INFO WHERE GENDER IS NOT NULL) U 
      ON U.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;